eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
microservice:
  userservice:
   endpoints:
    endpoint:
      uri:http://localhost:8080/user
  leaveservice:
   endpoints:
    endpoint:
     uri:http://localhost:8081/leaves      
